name: firebase_auth_repository

environment:
  sdk: ">=3.0.1 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  freezed: ^2.3.4

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.6.1
  freezed_annotation: ^2.2.0
  google_sign_in: ^6.1.2
