name: chat_repository

environment:
  sdk: ">=3.0.1 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  freezed: ^2.3.4
  json_serializable: ^6.7.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.0
